package moka;

import java.awt.event.KeyEvent;
import javax.swing.UIManager;

/**
 *
 * @author EvilZerg
 */
public class AskWindow extends javax.swing.JFrame {
    QuizManager engine;
    
    public AskWindow(QuizManager engine, String title, String msg, boolean isFuckVisible) {
        this.engine = engine;
        initComponents();
        
        this.setTitle(title);
        label.setText(msg);
        this.FuckButton.setVisible(isFuckVisible);
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnswerField = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        FuckButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        AnswerField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AnswerFieldKeyPressed(evt);
            }
        });

        OKButton.setText("OK");
        OKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKButtonMouseClicked(evt);
            }
        });

        label.setText("jLabel1");

        FuckButton.setText("Fuck off");
        FuckButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FuckButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OKButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FuckButton))
                    .addComponent(AnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addGap(9, 9, 9)
                .addComponent(AnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKButton)
                    .addComponent(FuckButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void OKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKButtonMouseClicked
        this.dispose();
        engine.setAnswer(AnswerField.getText());
    }//GEN-LAST:event_OKButtonMouseClicked

    private void AnswerFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AnswerFieldKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           OKButtonMouseClicked(null);
       }
    }//GEN-LAST:event_AnswerFieldKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FuckButtonMouseClicked(null);
    }//GEN-LAST:event_formWindowClosing

    private void FuckButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FuckButtonMouseClicked
        engine.engine.getFuckOff();
        this.dispose();
    }//GEN-LAST:event_FuckButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnswerField;
    private javax.swing.JButton FuckButton;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
