package moka;

import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.UIManager.*;
import javax.swing.ImageIcon;
        
/**
 *
 * @author EvilZerg
 */
public class MainWindow extends javax.swing.JFrame {
    public LogicEngine engine;
    private boolean isAchShowed;
    
    public MainWindow(LogicEngine engine){
        this.engine = engine;
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {}

        //adding status bar
        statusBar = new StatusBar();
        getContentPane().add(statusBar, java.awt.BorderLayout.SOUTH);
        
        initComponents();
        MainPanel.setBackground(new Color(255, 255, 255));
        MenuPanel.setBackground(new Color(255, 255, 255));
        AchievementsPanel.setBackground(new Color(255, 255, 255));
        engine.setGUIIcon(this);
        
        showAchivements();
        isAchShowed = true;
        
        //this.pack();
    }
    
    public void showAchivements(){
        ImageIcon imageIcon = new ImageIcon("lock.png");
        achLabel = new javax.swing.JLabel[12];
        for(int i=0; i<12; i++){
            achLabel[i] = new javax.swing.JLabel(imageIcon);
            achLabel[i].setLocation((i%3)*96, (i/3)*96);
            achLabel[i].setSize(96,96);
            AchievementsPanel.add(achLabel[i]);
        }    
    }
    
    public void hideAchivements(){
        for(int i=0; i<12; i++)
            achLabel[i].setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        QuizButton = new javax.swing.JButton();
        AddNewWordButton = new javax.swing.JButton();
        InTrayButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        DictionaryButton = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();
        AchievementsButton = new javax.swing.JToggleButton();
        AchievementsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Moka");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        QuizButton.setText("Start Quiz");
        QuizButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuizButtonMouseClicked(evt);
            }
        });
        QuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizButtonActionPerformed(evt);
            }
        });

        AddNewWordButton.setText("Add new word");
        AddNewWordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewWordButtonMouseClicked(evt);
            }
        });

        InTrayButton.setText("In tray");
        InTrayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InTrayButtonMouseClicked(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        DictionaryButton.setText("Dictionary");
        DictionaryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DictionaryButtonMouseClicked(evt);
            }
        });

        SettingsButton.setText("Settings");

        AchievementsButton.setText("Achievements");
        AchievementsButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AchievementsButtonStateChanged(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DictionaryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuizButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddNewWordButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(InTrayButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AchievementsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuizButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddNewWordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InTrayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DictionaryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AchievementsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettingsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AchievementsPanelLayout = new javax.swing.GroupLayout(AchievementsPanel);
        AchievementsPanel.setLayout(AchievementsPanelLayout);
        AchievementsPanelLayout.setHorizontalGroup(
            AchievementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );
        AchievementsPanelLayout.setVerticalGroup(
            AchievementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addComponent(AchievementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AchievementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewWordButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewWordButtonMouseClicked
        engine.addNewWord();
    }//GEN-LAST:event_AddNewWordButtonMouseClicked

    private void QuizButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuizButtonMouseClicked
        engine.startQuiz();
    }//GEN-LAST:event_QuizButtonMouseClicked

    private void InTrayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InTrayButtonMouseClicked
        this.dispose();
        //engine.runTray();
    }//GEN-LAST:event_InTrayButtonMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        engine.runTray();
    }//GEN-LAST:event_formWindowClosed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        engine.closeApplication();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void QuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuizButtonActionPerformed

    private void DictionaryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DictionaryButtonMouseClicked
        engine.showDictionary();
    }//GEN-LAST:event_DictionaryButtonMouseClicked

    private void AchievementsButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AchievementsButtonStateChanged
/*        if (isAchShowed){
            isAchShowed = false;
            hideAchivements();
        } else {
            isAchShowed = true;
            showAchivements();
        }  */      
    }//GEN-LAST:event_AchievementsButtonStateChanged

    //private Container pane;
    private javax.swing.JLabel achLabel[];
    private StatusBar statusBar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AchievementsButton;
    private javax.swing.JPanel AchievementsPanel;
    private javax.swing.JButton AddNewWordButton;
    private javax.swing.JButton DictionaryButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton InTrayButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton QuizButton;
    private javax.swing.JButton SettingsButton;
    // End of variables declaration//GEN-END:variables
}
